Use os.unlink instead of temp.unlink for python3.4
Python 3.4 threw an AttributeError for: '_io.BufferedRandom'
object has no attribute 'unlink'.  Python 3.2 and 3.3 passed
without a hitch.  I wonder if it was intentional.